In [ ]:
#similar to pandas

In [2]:
#numpy is matlab pythonic library

In [6]:
import numpy as np

In [3]:
l=[1,2,3,4]
type(l)

list

In [4]:
a=np.array(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a1=np.array([[1,2,3],[3,4,5]])

In [8]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [9]:
a2=np.array([[[1,2,3],[4,.5,6]]])

In [10]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [11]:
#dimensions of a,a1,a2
a.ndim

1

In [12]:
a1.ndim

2

In [14]:
a2.ndim

3

In [15]:
a3=np.array([[[1,2,3],[4,.5,6]],[[1,2,3],[4,.5,6]],[[1,2,3],[4,.5,6]]])

In [16]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [17]:
a3.ndim

3

*Matrices*

In [22]:
# matrix has always 2-D
l=[1,2,34,45]
m=np.matrix(l)
m

matrix([[ 1,  2, 34, 45]])

In [20]:
np.asanyarray(l)

array([ 1,  2, 34, 45])

In [23]:
#keeps matrix as matrix itself
np.asanyarray(m)

matrix([[ 1,  2, 34, 45]])

*Deep Copy and Swallo copy:*

In [24]:
#swallow copy,same memory ,affects the memory
a1=a

In [25]:
a1

array([1, 2, 3, 4])

In [26]:
a

array([1, 2, 3, 4])

In [28]:
#value changingin a
a[0]=10

In [29]:
a

array([10,  2,  3,  4])

In [30]:
#also changed in a1
a1

array([10,  2,  3,  4])

In [31]:
a1[3]=50

In [32]:
a1

array([10,  2,  3, 50])

In [33]:
a

array([10,  2,  3, 50])

In [34]:
#value changed in both

In [35]:
# Deep copy ,didnt affect others memory ,pointint to other memory
a2=np.copy(a)


In [36]:
a2

array([10,  2,  3, 50])

In [37]:
a2[2]=30

In [38]:
a2

array([10,  2, 30, 50])

In [39]:
a

array([10,  2,  3, 50])

In [40]:
a2

array([10,  2, 30, 50])

*FromFunction:*

In [41]:
#fromfunction
np.fromfunction(lambda i,j : i==j,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [45]:
np.random.rand(2,3,2)

array([[[0.7774346 , 0.47673516],
        [0.0873851 , 0.78934989],
        [0.70471556, 0.8059546 ]],

       [[0.15751529, 0.00854698],
        [0.29611669, 0.17671503],
        [0.47296803, 0.44231537]]])

In [46]:
np.random.rand(2,3,2,2)

array([[[[0.6952751 , 0.61315034],
         [0.16907295, 0.56694008]],

        [[0.84074146, 0.27250952],
         [0.29918356, 0.18891655]],

        [[0.26143972, 0.89856983],
         [0.48021516, 0.40311507]]],


       [[[0.28942319, 0.347604  ],
         [0.07334045, 0.74247521]],

        [[0.76160274, 0.8088377 ],
         [0.0028805 , 0.18156769]],

        [[0.41590111, 0.91262777],
         [0.62917013, 0.46869717]]]])

In [48]:
np.random.rand(2,3,4)

array([[[0.50549291, 0.70643531, 0.02571188, 0.79455098],
        [0.55313319, 0.0273927 , 0.27361059, 0.35108697],
        [0.80510013, 0.70599779, 0.16337064, 0.08406878]],

       [[0.41612829, 0.02016884, 0.45819296, 0.94955068],
        [0.16340591, 0.82765028, 0.35384445, 0.71727521],
        [0.25474255, 0.58451287, 0.14630481, 0.97574621]]])

In [57]:
#randn 
d=np.random.randn(3,4)
d

array([[ 1.56288056,  0.59147676,  0.06934907, -0.2912359 ],
       [ 0.64997744,  2.2266143 , -1.04093604,  0.44720836],
       [-1.15214879, -1.76140687, -2.5280613 ,  0.04798501]])

In [53]:
#randint
#0,10 taking random values values upto 10
#(4X4) is matrix
np.random.randint(0,10,(4,4))

array([[4, 7, 8, 4],
       [9, 3, 2, 1],
       [6, 5, 0, 2],
       [1, 6, 9, 9]])

In [62]:
d1=np.random.randint(0,10,(4,4,2))

In [63]:
d1

array([[[0, 6],
        [4, 9],
        [1, 2],
        [4, 1]],

       [[3, 5],
        [5, 1],
        [0, 1],
        [9, 8]],

       [[7, 3],
        [4, 2],
        [0, 5],
        [6, 8]],

       [[3, 1],
        [5, 0],
        [0, 8],
        [8, 9]]])

In [58]:
#using it in pandas
d

array([[ 1.56288056,  0.59147676,  0.06934907, -0.2912359 ],
       [ 0.64997744,  2.2266143 , -1.04093604,  0.44720836],
       [-1.15214879, -1.76140687, -2.5280613 ,  0.04798501]])

In [59]:
import pandas as pd

In [60]:
pd.DataFrame(d)

0         1         2         3
0  1.562881  0.591477  0.069349 -0.291236
1  0.649977  2.226614 -1.040936  0.447208
2 -1.152149 -1.761407 -2.528061  0.047985

In [72]:
#only allows 2-d
pd.DataFrame(d1)

ValueError: Must pass 2-d input. shape=(4, 4, 2)

In [71]:
#with the help of Reshape function by factors = matrice elements
pd.DataFrame(d1.reshape(8,4))

0  1  2  3
0  0  6  4  9
1  1  2  4  1
2  3  5  5  1
3  0  1  9  8
4  7  3  4  2
5  0  5  6  8
6  3  1  5  0
7  0  8  8  9

In [73]:
d1

array([[[0, 6],
        [4, 9],
        [1, 2],
        [4, 1]],

       [[3, 5],
        [5, 1],
        [0, 1],
        [9, 8]],

       [[7, 3],
        [4, 2],
        [0, 5],
        [6, 8]],

       [[3, 1],
        [5, 0],
        [0, 8],
        [8, 9]]])

In [1]:
import numpy as np

In [2]:
range(10)

range(0, 10)

In [6]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
list(range(3,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [26]:
#linespace
np.linspace(0,100,20,retstep=True)

(array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
         21.05263158,  26.31578947,  31.57894737,  36.84210526,
         42.10526316,  47.36842105,  52.63157895,  57.89473684,
         63.15789474,  68.42105263,  73.68421053,  78.94736842,
         84.21052632,  89.47368421,  94.73684211, 100.        ]),
 5.2631578947368425)

In [27]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [28]:
#zeroes function
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((3,3,4))*4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
np.ones((3,3,3))*5

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [40]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
#identity matrices
h=np.eye(4)

In [5]:
h

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
#shape
h.size

16

In [7]:
h.ndim

2

In [7]:
#i have a array ,
a1=np.random.randint(0,100,(3,4))

In [8]:
a1

array([[18, 95, 59, 42],
       [42, 94, 63, 53],
       [37, 52, 82, 70]])

In [9]:
a1[2][3]

70

In [17]:
a1[[0,1],0:2]

array([[18, 95],
       [42, 94]])

In [10]:
import pandas as pd

In [11]:
a11=pd.DataFrame(a1)

In [18]:
a11


0   1   2   3
0  18  95  59  42
1  42  94  63  53
2  37  52  82  70

In [19]:
a1

array([[18, 95, 59, 42],
       [42, 94, 63, 53],
       [37, 52, 82, 70]])

In [24]:
#[1,2]row and 3 is column
a1[[1,2],3]

array([53, 70])

In [28]:
m1=np.random.randint(1,3,(3,3))
m1

array([[1, 2, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [29]:
m2=np.random.randint(2,4,(3,3))

In [30]:
m2

array([[2, 2, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [31]:
#this is index wise multplication
m1*m2

array([[2, 4, 3],
       [3, 3, 3],
       [6, 6, 6]])

In [35]:
# Matrix multiplication
m1@m2

array([[11, 11, 12],
       [ 8,  8,  9],
       [16, 16, 18]])

In [37]:
#to find pow
pow(m1,2)

array([[1, 4, 1],
       [1, 1, 1],
       [4, 4, 4]])

In [38]:
#find square root
np.sqrt(m1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

In [39]:
#to find log
np.log10(m1)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.     ],
       [0.30103, 0.30103, 0.30103]])

In [40]:
np.exp(m1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [41]:
m1**2

array([[1, 4, 1],
       [1, 1, 1],
       [4, 4, 4]])